class AppStrings {
  static const String title = "Hello from CleanForge";
  static const String pageNotFound = "Page Not Found";
  static const String homeText = "Home Widget";
  static const String homeDescText = "All the files and folder for this project is generated by CleanForge";
  static const String homeNoteText = "By default the app will take system theme";
}
